### ISSUE TITLE
Trying to compile for webassembly

### ISSUE THREAD

**Issue by kryptoniancode** [leotaku/web-push-native#9]
I have created a hello_wasm project using https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm

This is Cargo.toml
```toml
[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rust-crypto-wasm = "0.3.1"
aes-gcm = "0.10.3"
getrandom = { version = "0.2", features = ["js"] }
ece-native = "0.4.0"
once_cell = "1.19.0"
base64ct = { version = "1.6.0", features = ["alloc", "std"] }
web-push-native = "0.4.0"
```

This is html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="module">
        import init, { test_encryption_decryption_with_serialization } from "./pkg/hello_wasm.js";
        init().then(() => {
            test_encryption_decryption_with_serialization();
        });
    </script>
</head>

<body>

</body>

</html>
```

This is src/lib.rs

```rust
extern crate crypto;

use crypto::{digest::Digest, sha2::Sha256};
use wasm_bindgen::prelude::*;

use base64ct::{Base64UrlUnpadded, Encoding};

use web_push_native::{
    decrypt, encrypt,
    jwt_simple::{self, reexports::serde_json, algorithms::ES256KeyPair},
    p256::{self, PublicKey}, Auth, WebPushBuilder,
};

use web_push_native::p256::elliptic_curve::sec1::ToEncodedPoint;

#[wasm_bindgen]
pub fn test_encryption_decryption_with_serialization() {
    // Placeholders for variables provided by individual clients. In most cases,
    // these will be retrieved in-browser by calling `pushManager.subscribe` on
    // a service worker registration object.
    const ENDPOINT: &str = "";
    const P256DH: &str = "";
    const AUTH: &str = "";

    // Placeholder for your private VAPID key. Keep this private and out of your
    // source tree in real projects!
    const VAPID: &str = "";

    let key_pair = ES256KeyPair::from_bytes(&Base64UrlUnpadded::decode_vec(VAPID).unwrap()).unwrap();
    let builder = WebPushBuilder::new(
        ENDPOINT.parse().unwrap(),
        PublicKey::from_sec1_bytes(&Base64UrlUnpadded::decode_vec(P256DH).unwrap()).unwrap(),
        Auth::clone_from_slice(&Base64UrlUnpadded::decode_vec(AUTH).unwrap()),
    )
    .with_vapid(&key_pair, "mailto:john.doe@example.com");

    let len = builder.build("content");   
}
```

compile, run and open in browser
```
wasm-pack build --target web --debug
python -m http.server
```

error in console log in chrome dev tools
```js
Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (hello_wasm_bg.wasm:0x17ab2b)
    at rust_panic (hello_wasm_bg.wasm:0x17a7bc)
    at std::panicking::rust_panic_with_hook::h62090d3fc0630473 (hello_wasm_bg.wasm:0x13ddaa)
    at std::panicking::begin_panic_handler::{{closure}}::h823c80ef219a166d (hello_wasm_bg.wasm:0x14d820)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hcc7222b556723586 (hello_wasm_bg.wasm:0x17aad1)
    at rust_begin_unwind (hello_wasm_bg.wasm:0x170a9f)
    at core::panicking::panic_fmt::hd79411a297d06dc8 (hello_wasm_bg.wasm:0x174955)
    at core::panicking::assert_failed_inner::h003d4b5b03930769 (hello_wasm_bg.wasm:0x110a73)
    at core::panicking::assert_failed::h985a4a1c1b7563ab (hello_wasm_bg.wasm:0x160a2b)
    at <&generic_array::GenericArray<T,N> as core::convert::From<&[T]>>::from::h68a9a2e49c3eb98d (hello_wasm_bg.wasm:0x1344df)
```
